settings:
  project_name: aic-hcmc2020  # also the folder name of the dataset that under data_path folder
  train_set: images
  val_set: images

  # mean and std in RGB order, actually this part should remain unchanged as long as your dataset is similar to coco.
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

  # this is coco anchors, change it if necessary
  anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
  anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'

  # must match your dataset's category_id.
  # category_id is one_indexed,
  # for example, index of 'car' here is 2, while category_id of is 3
  obj_list: ['motorcycle', 'car', 'bus', 'truck']